[package]
name = "rfd-notify"
version = "0.1.0"
authors = ["Dave Gallant <davegallant@gmail.com>"]
edition = "2018"

[dependencies]
sendgrid = { version = "0.11.3", features = ["rustls"] }
toml = "0.5.6"
serde_derive = "1.0.112"
serde = "1.0.112"
