[package]
name = "rfd-notify"
version = "0.1.2"
authors = ["Dave Gallant <davegallant@gmail.com>"]
edition = "2018"

[dependencies]
sendgrid = { version = "0.13.0", features = ["rustls"] }
toml = "0.5.7"
serde_derive = "1.0.112"
serde = "1.0.116"
reqwest = { version = "0.10", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "0.2", features = ["full"] }
serde_json = "1.0.58"
log = "0.4"
pretty_env_logger = "0.4.0"
regex = "1.3.9"
rust-crypto = "^0.2"
sled = "0.34.4"
clap = "2.33.3"
