name: Publish Container
on: [push]

jobs:
  push_to_registry:
    name: Push to container registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        id: prep
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/rfd-notify
          VERSION=${GITHUB_REF##*/}

          if [[ $GITHUB_REF == refs/heads/main ]]; then
            VERSION=latest
          fi

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi

          TAGS="${IMAGE_NAME}:${VERSION}"

          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${IMAGE_NAME}:latest"
          fi

          echo ::set-output name=tags::${TAGS}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Packages
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}

