name: Pylint

on: [push, pull_request]

env:
  PYTHON_VERSION: "3.11"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          pip install poetry==1.3.2
          poetry install

      - name: Lint
        run: poetry run pylint ./rfd_notify
